services:
  hub:
    image: eternalq/gtnh-hub
    container_name: gtnh-hub
    restart: unless-stopped
    environment:
      # CONFIG_PATH: /root/config.yaml
      DISCORD_BOT_TOKEN: bot_token
      DISCORD_WEBHOOK_ID: webhook_id
      DISCORD_WEBHOOK_TOKEN: webhook_token
      MCS_BASE_URL: http://host.docker.internal:23333
      MCS_API_KEY: mcs_api_key
      RCON_PASSWORD: rcon_password
    volumes:
      - ./config.yaml:/root/config.yaml:ro
    ports:
      - 5665:5665